language: objective-c
osx_image: xcode8.3
xcode_sdk: iphonesimulator10.3

env:
  matrix:
    - TEST_TYPE=iOS
-before_install:
 - |
    gem install xcpretty -N --no-ri --no-rdoc
script:
- |
    ./setup.sh
    if [ "$TEST_TYPE" = iOS ]; then
      set -o pipefail
      xcodebuild -project NetworkingKit.xcodeproj -scheme NetworkingKit-iOS | xcpretty
    fi
