language: objective-c
osx_image: xcode8.3
xcode_project: NetworkingKit.xcodeproj
xcode_scheme: NetworkingKit-iOS
xcode_sdk: iphonesimulator10.3
script: xcodebuild clean build -workspace NetworkingKit.xcworkspace -scheme NetworkingKit-iOS
